apiVersion: v1
kind: Service
metadata:
  name: "hello-world"
  labels:
    app: "hello-world"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30555
  selector:
    app: "hello-world"
  type: LoadBalancer
